name: get-uncommitted-changes
description: "Stages all changes, lists files, unstages all changes"

runs:
  using: "composite"
  steps:
    - name: Execute git script
      id: git
      shell: bash
      run: |
        git add --all
        changes=$(git diff --staged --name-only)
        echo "files=$(for file in $(echo $changes); do echo "'$file' "; done | tr '\n' ' ')" >> $GITHUB_OUTPUT
        echo "count=$(wc -l <<< $changes | xargs)" >> $GITHUB_OUTPUT
        git reset .
