name: pr-filter
description: Checks if PR meets certian criteria

inputs:
  paths:
    description: Semicolon separated globs
    required: false

runs:
  using: node16
  main: dist/index.js

outputs:
  result:
    description: true if all criteria met, otherwise false
