name: CD

on:
  push:
    branches:
      - releases/*
    tags:
      - v*
    paths:
      - package.json

jobs:

  hello:

    runs-on: windows-latest
    name: Hello
    
    steps:
      - name: print
        run: echo hello