name: Changed Files Test
on:
  pull_request:

jobs:

  prFilter:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter
        id: filter
        uses: ./.github/actions/pr-filter
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: '**;!**/*.yml'
