name: Check

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:

  check-semver-tag:

    name: PR must have SemVer label
    runs-on: ubuntu-latest

    steps:
      - name: Check 2
        env:
          INTERNAL:  ${{contains(github.event.pull_request.labels.*.name, 'internal') && 1 || 0}}
          PATCH:  ${{contains(github.event.pull_request.labels.*.name, 'patch') && 1 || 0}}
          MINOR:  ${{contains(github.event.pull_request.labels.*.name, 'minor') && 1 || 0}}
          MAJOR:  ${{contains(github.event.pull_request.labels.*.name, 'major') && 1 || 0}}
        run: >
          if [ $((INTERNAL + PATCH + MINOR + MAJOR)) -ne 1 ]
            then
              echo "PR must have one and only one tag of the following: internal, patch, minor, major. "
              exit 1
          fi

      - name: Check labels
        env:
          INTERNAL:  ${{contains(github.event.pull_request.labels.*.name, 'internal') && 1 || 0}}
          PATCH:  ${{contains(github.event.pull_request.labels.*.name, 'patch') && 1 || 0}}
          MINOR:  ${{contains(github.event.pull_request.labels.*.name, 'minor') && 1 || 0}}
          MAJOR:  ${{contains(github.event.pull_request.labels.*.name, 'major') && 1 || 0}}
        run: >
          if [ $((INTERNAL + PATCH + MINOR + MAJOR)) -ne 1 ]
            then
              echo "PR must have one and only one tag of the following: internal, patch, minor, major. "
              exit 1
          fi
