name: Check

on:
  pull_request:
    branches:
      - '*'

jobs:

  check-version:

    name: Check version bumped
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check
        run: git show

        
      