name: Check

on:
  pull_request:
    branches:
      - '*'

jobs:

  check-version:

    name: Check version bumped
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print
        run: git log -1 --pretty=format:"%s"

        
      