name: Check

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:

  check-semver-tag:

    name: Should have SemVer tag
    runs-on: ubuntu-latest

    steps:

      - name: Check tag
        run: echo ${{ join(github.event.pull_request.labels.*.name, ', ') }}
