name: Check
on:
  pull_request:
    types: 
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled
jobs:

  check-version-pr:
    name: Version Bump
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Detect version bump
        id: versionBump
        uses: ./.github/actions/detect-version-bump

      - name: Check version is the only change
        if: steps.versionBump.outputs.changed       
        run: |
          stat=$(git diff HEAD^ HEAD --shortstat)
          
          if ! [[ "$stat" =~ (1 *file *changed.*1 *insertion.*1 *deletion) ]]
          then
            echo "PR with version bump must have no other changes"
            exit 1
          fi
