name: Check

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:

  check-semver-tag:

    name: Should have SemVer tag
    runs-on: ubuntu-latest
    env:
      INTERNAL:  ${{contains(github.event.pull_request.labels.*.name, 'internal') && 1 || ''}}
      PATCH:  ${{contains(github.event.pull_request.labels.*.name, 'patch') && 1 || ''}}
      MINOR:  ${{contains(github.event.pull_request.labels.*.name, 'minor') && 1 || ''}}
      MAJOR:  ${{contains(github.event.pull_request.labels.*.name, 'major') && 1 || ''}}

    steps:

      - name: Print Count
        env:
          INTERNAL:  ${{contains(github.event.pull_request.labels.*.name, 'internal') && 1 || 0}}
          PATCH:  ${{contains(github.event.pull_request.labels.*.name, 'patch') && 1 || 0}}
          MINOR:  ${{contains(github.event.pull_request.labels.*.name, 'minor') && 1 || 0}}
          MAJOR:  ${{contains(github.event.pull_request.labels.*.name, 'major') && 1 || 0}}
        run: >
          if [ $((INTERNAL + PATCH + MINOR + MAJOR)) -eq 1 ]
            then
              echo "correct";
            else
              echo "incorrect"
          fi
          
      - name: Check
        if:  format('{0}{1}{2}{3}', env.INTERNAL, env.PATCH, env.MINOR, env.MAJOR) != 1
        run: echo -${{ env.INTERNAL }}${{ env.PATCH }}${{ env.MINOR }}${{ env.MAJOR }}-
