name: Check

on:
  pull_request:
    branches:
      - '*'

jobs:

  check-version:

    name: Check version bumped
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check
        run: git diff HEAD^ HEAD -U0 package.json | tail -n +6 | grep "^\+.*\"version\":" || exit 1

      - name: Print
        run: git branch
