name: Check

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:

  check-semver-tag:

    name: Should have SemVer tag
    runs-on: ubuntu-latest

    steps:

      - name: Print Count
        env:
          INTERNAL:  ${{contains(github.event.pull_request.labels.*.name, 'internal') && 1 || ''}}
          PATCH:  ${{contains(github.event.pull_request.labels.*.name, 'patch') && 1 || ''}}
          MINOR:  ${{contains(github.event.pull_request.labels.*.name, 'minor') && 1 || ''}}
          MAJOR:  ${{contains(github.event.pull_request.labels.*.name, 'major') && 1 || ''}}
        run: >
          [1 -eq ($INTERNAL + $PATCH + $MINOR + $MAJOR)] && echo "correct" || echo "incorrect"
