name: Common Tests

on:
  push:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:

    - name: Get sources
      uses: actions/checkout@v4

    # - name: Get changed files
    #   id: verify-changed-files
    #   uses: tj-actions/verify-changed-files@v20
    #   with:
    #     files: |
    #       **/*

    # - name: Check all changed files
    #   run: |
    #     for file in "${{ steps.verify-changed-files.outputs.all_changed_files }}"; do
    #       echo "$file"
    #     done

    - name: Get changed files
      id: changed-files
      uses: IlyaKhD/github-actions/get-changed-files@khd/fix-empty-paths-case
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        paths: '**/*'
        output: changed-files.json

    - name: Print files 1
      run: |
        for file in ${{ steps.changed-files.outputs.files }}; do
          echo "$file"
        done

    - name: Print files 2
      run: |
        for file in $( jq -r '.files.[]' <<< '${{ steps.changed-files.outputs.json }}' ); do
          echo "$file"
        done

    - name: Print count 1
      run: |
        echo "${{ steps.changed-files.outputs.count }}"

    - name: Print count 2
      env:
        COUNT: ${{ fromJSON(steps.changed-files.outputs.json).count }}
      run: |
        echo "$COUNT"

    - name: Check count 1
      if: steps.changed-files.outputs.count > 2
      run: |
        echo "${{ steps.changed-files.outputs.count }}"

    - name: Check count 2
      if: fromJSON(steps.changed-files.outputs.json).count > 2
      run: |
        echo "${{ fromJSON(steps.changed-files.outputs.json).count }}"
          
    - name: Print file 1
      run: |
        cat changed-files.json

    - name: Save file
      run: |
        jq -r '[.files[] | {filename: .path}]' <<< '${{ steps.changed-files.outputs.json }}' > changed-files-2.json

    - name: Print file 2
      run: |
        cat changed-files-2.json

    - name: Print JSON
      run: |
        jq -r <<< '${{ steps.changed-files.outputs.json }}'
