name: Common Tests

on:
  pull_request:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:

    - name: Get sources
      uses: actions/checkout@v4

    # - name: Get changed files
    #   id: changed-files
    #   uses: tj-actions/verify-changed-files@v20
    #   with:
    #     files: |
    #       **/*

    - name: Get changed files
      id: changed-files
      uses: DevExpress/github-actions/get-changed-files@v1
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        paths: '**/*'
        output: changed-files.json
          
    - name: Echo
      run: |
        cat changed-files.json
