name: Common Tests

on:
  push:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:

    - name: Get sources
      uses: actions/checkout@v4
    
    - name: Make changes
      run: |
        rm -f feature-2.ts
        mv feature-3.ts feature-renamed.ts
        touch new-file.txt
        echo "\nchanges" >> README.md


    - name: Get Uncommitted Changes
      id: uncommittedChanges
      uses: ./.github/actions/get-uncommitted-changes

    - name: Print
      run: |
        echo "Uncommited files count: ${{ steps.uncommittedChanges.outputs.count }}"
        for file in ${{ steps.uncommittedChanges.outputs.files }}; do
          echo "$file"
        done