name: Common Tests

on:
  push:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:

    - name: Get sources
      uses: actions/checkout@v4

    # - name: Get changed files
    #   id: verify-changed-files
    #   uses: tj-actions/verify-changed-files@v20
    #   with:
    #     files: |
    #       **/*

    # - name: Check all changed files
    #   run: |
    #     for file in "${{ steps.verify-changed-files.outputs.all_changed_files }}"; do
    #       echo "$file"
    #     done

    - name: Get changed files
      id: changed-files
      uses: IlyaKhD/github-actions/get-changed-files@khd/fix-empty-paths-case
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        paths: '**/*'
        output: changed-files.json

    - name: Print files
      run: |
        for file in $( jq -r '.files.[]' <<< '${{ steps.changed-files.outputs.json }}' ); do
          echo "$file"
        done

    - name: Print count
      run: |
        echo "${{ steps.changed-files.outputs.count }}"

    - name: Print count
      if: steps.changed-files.outputs.count > 2
      run: |
        echo "${{ steps.changed-files.outputs.count }}"

          
    - name: Print file
      run: |
        cat changed-files.json
