name: Common Tests

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v4
      with:
        sparse-checkout: /scripts
        sparse-checkout-cone-mode: false
    - run: npm i
    - name: step1
      env:
        E1: ${{ github.repository_owner }}
      run: npm run ts-node scripts/script1;
