name: Common Tests

on:
  push:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:

    - name: Get sources
      uses: actions/checkout@v4

    - name: Get changed files
      id: verify-changed-files
      uses: tj-actions/verify-changed-files@v20
      with:
        files: |
          **/*

    - name: Check all changed files
      run: |
        for file in "${{ steps.verify-changed-files.outputs.all_changed_files }}"; do
          echo "$file"
        done

    - name: Get changed files
      id: changed-files
      uses: DevExpress/github-actions/get-changed-files@main
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        paths: '**/*'
        output: changed-files.json
          
    - name: Echo
      run: |
        cat changed-files.json
