name: Dispatching Workflow

on:
  pull_request:

jobs:

  trigger:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - run: echo {{ github.head_ref }}

      - name: Run Stubs Workflow
        if: steps.filter.outputs.result != 'true'
        run: gh workflow run child.yml
