name: Inputs Test

on:
  workflow_dispatch:
    inputs:
      filter:
        type: string
        description: Package file pattern
        required: false
      move-next-tag:
        type: boolean
        description: Move 'next' tag
        required: false
        default: false
      move-stable-tag:
        type: boolean
        description: Move 'stable' tag
        required: false
        default: false

env:
  FILTER: ${{ (github.event_name == 'workflow_dispatch' && inputs.filter) || (github.event_name != 'workflow_dispatch' && '') }}
  MOVE_NEXT_TAG: ${{ (github.event_name == 'workflow_dispatch' && inputs.move-next-tag) || (github.event_name != 'workflow_dispatch' && true) }}

jobs:

  publish:
    name: Publish packages
    runs-on: ubuntu-latest

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - run: ls
      - run: ls | grep -E -i ''
      - run: ls | grep -E -i '$FILTER'
      - run: echo "${{ toJson(inputs.move-next-tag) }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "$MOVE_NEXT_TAG"
      
      - name: Move 'next' tag -7
        if: ${{ env.MOVE_NEXT_TAG == 'true' }}
        run: echo "$MOVE_NEXT_TAG"

      - name: Move 'next' tag -6
        if: "${{ env.MOVE_NEXT_TAG == true }}"
        run: echo "$MOVE_NEXT_TAG"

      - name: Move 'next' tag -5
        if: env.MOVE_NEXT_TAG == true
        run: echo "$MOVE_NEXT_TAG"

      - name: Move 'next' tag -4
        if: ${{ env.MOVE_NEXT_TAG == true }}
        run: echo "$MOVE_NEXT_TAG"

      - name: Move 'next' tag -3
        if: ${{ env.MOVE_NEXT_TAG }}
        run: echo "$MOVE_NEXT_TAG"

      - name: Move 'next' tag -2
        if: env.MOVE_NEXT_TAG
        run: echo "$MOVE_NEXT_TAG"


      - name: Move 'next' tag -1
        if: ${{ inputs.move-next-tag }}
        run: echo -1

      - name: Move 'next' tag 1
        if: "${{ inputs.move-next-tag }}"
        run: echo 1

      - name: Move 'next' tag 2
        if: "${{ inputs.move-next-tag == true }}"
        run: echo 2

      - name: Move 'next' tag 3
        if: "${{ inputs.move-next-tag == 'true' }}"
        run: echo 3

      - name: Move 'next' tag 4
        run: |
          if [ ${{ toJSON(inputs.move-next-tag) }} = true ]; then echo 41;fi;
          if [ ${{ toJSON(inputs.move-stable-tag) }} = true ]; then echo 42;fi;

