name: Input Matrix Test

on:
  workflow_dispatch:
    inputs:
      pattern:
        type: string
        description: Package file pattern
        required: false

jobs:
  discover:
    name: Discover Files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.step1.outputs.files }}
    steps:
      - name: Get sources
        uses: actions/checkout@v4
      - id: step1
        run: ls | grep --extended-regexp --ignore-case --regexp='${{ inputs.pattern }}' | sed -r 's/^(.*)$/"\1"/g' | paste -sd "," - | sed -r 's/(.*)/files=[\1]/' >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v3
        with:
          name: files
          path: ./*

  print:
    name: Print files
    runs-on: ubuntu-latest
    needs: discover
    strategy:
      matrix:
        file: ${{ fromJSON(needs.discover.outputs.files) }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: files
      - env:
          FILE: ${{ matrix.file }}
        run: echo "$FILE"
      - env:
          FILE: ${{ matrix.file }}
        run: cat $FILE
