name: Input Matrix Test

on:
  workflow_dispatch:
    inputs:
      pattern:
        type: string
        description: Package file pattern
        required: false

jobs:
  discover:
    name: Discover Files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.step1.outputs.files }}
    steps:
      - name: Get sources
        uses: actions/checkout@v4
      - id: step1
        run: ls | grep --extended-regexp --ignore-case --regexp='${{ inputs.pattern }}' | sed -r 's/^(.*)$/"\1"/g' | paste -sd "," - | sed -r 's/(.*)/files=[\1]/' >> "$GITHUB_OUTPUT"
      - run: ls
      - run: ls | grep --extended-regexp --ignore-case --regexp='${{ inputs.pattern }}'

  print:
    name: Print files
    runs-on: ubuntu-latest
    needs: discover
    steps:
      - env:
          FILES: ${{needs.discover.outputs.files}}
        run: echo "$FILES"
      
