name: PR Filter Test
on:
  push:
    branches: master
  pull_request:

jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify version change
        uses: IlyaKhD/github-actions/verify-version-change@test
