name: Path dependent workflow
on:
  push:
    branches: 
      - master
    paths:
      - '**'
      - '!**/*.md'
jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: echo 123