name: Path dependent workflow
on:
  pull_request:
    paths:
      - '**/*.yml'
    paths-ignore:
      - '**/*'

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: echo 123

# change1