name: PR Filter Test
on:
  push:
    branches: master
  pull_request:

jobs:

  prFilter:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter
        id: filter
        uses: ./.github/actions/pr-filter
        with:
          paths: '**;!**/*.yml'

  required1:
    name: 'required'
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:
      - run: exit 0

  required2:
    name: 'required'
    if: false
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:
      - run: exit 1
