name: PR Filter Test
on:
  push:
  pull_request:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:

      - name: Get sources
        uses: actions/checkout@v4

      - name: History
        run: git log -n 10 --pretty=format:"%H"

      - name: PR Filter
        id: prFilter
        uses: ./.github/actions/pr-filter

      - name: Check PR has one severity label
        if: steps.prFilter.outputs.result == 'false'
        
        run: |
          echo 123
