name: PR Filter Test
on:
  push:
    branches: master
  pull_request:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:

      - name: Get sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: History
        run: git log -n 10 --pretty=format:"%H"

      - name: PR Filter
        id: prFilter
        uses: ./.github/actions/pr-filter
        with:
          paths: '**;!**/*.md'

      - name: Run step if paths filter met
        if: steps.prFilter.outputs.result == 'true'
        
        run: |
          echo 123
