name: PR Filter Test
on:
  push:
    branches: master
  pull_request:

jobs:

  prFilter:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.test }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter
        id: filter
        uses: ./.github/actions/pr-filter
        with:
          paths: '**;!**/*.md'

  job2:
    needs: prFilter
    if: needs.prFilter.outputs.success
    runs-on: ubuntu-latest

    steps:
      - run: echo 123
