name: PR Filter Test
on:
  push:
  pull_request:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:

      - name: Print Base Ref 1
        run: echo "Base ref: ${{ github.event.pull_request.base.ref }}"

      - name: Get sources
        uses: actions/checkout@v4
#        with:
#          ref: ${{ github.event.pull_request.base.ref }}

      # - name: Print Base Ref 2
      #   run: echo "Base ref: ${{ github.event.pull_request.base.ref }}"

      - name: fetch
        run: git fetch origin

      - name: History
        run: git log -n 10 --pretty=format:"%H"

      - name: PR Filter
        id: prFilter
        uses: ./.github/actions/pr-filter

      - name: Check PR has one severity label
        if: steps.prFilter.outputs.result == 'false'
        
        run: |
          echo 123
