name: PR Filter Test
on:
  push:
    branches: master
  pull_request:

jobs:

  prFilter:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter
        id: filter
        uses: ./.github/actions/pr-filter
        with:
          paths: '**;!**/*.yml'


  filteredMatrixJob:
    needs: prFilter
    if: needs.prFilter.outputs.success == 'true'
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        a: [ 'a', 'b' ]
        b: [ 1, 2 ]

    steps:
      - run: echo ${{ matrix.a }} - ${{ matrix.b }}
