name: PR Filter Test
on:
  push:
    branches: master
  pull_request:

jobs:

  prFilter:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter
        id: filter
        uses: ./.github/actions/pr-filter
        with:
          paths: '**;!**/*.md'


  filteredJob:
    needs: prFilter
    if: needs.prFilter.outputs.success != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: |
          while true; do
            echo "This job is still running..."
            sleep 60  # Wait for 60 seconds before printing the message again
          done

  filteredStubJob:
    name: 'required'
    needs: [ filteredJob ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
