name: PR Filter Test
on:
  push:
    branches: master
  pull_request:

jobs:

  prFilter:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter
        id: filter
        uses: ./.github/actions/pr-filter
        with:
          paths: '**;!**/*.yml'

  fail1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "error message" >&2 && exit 1

  fail2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: core.setFailed('error message')

  fail3:
    runs-on: ubuntu-latest
    steps:
      - name: exit with error
        run: |
          echo "::error::Changes in apps/**/*.md shouldn't be mixed with changes in other files"
          exit 1
