name: PR Filter Test Stub
on:
  push:
    branches: master
  pull_request:

jobs:

  prFilter:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.filter.outputs.result }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter
        id: filter
        uses: ./.github/actions/pr-filter
        with:
          paths: '**;!**/*.md;!**/*.yml'

  anotherMatrixJobStub:
    name: Another Matrix Job ${{ matrix.a }} - ${{ matrix.b }}
    needs: prFilter
    if: always() && needs.prFilter.outputs.success != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: ['a', 'b']
        b: [0, 1]

    steps:
      - run: echo ${{ matrix.a }} - ${{ matrix.b }} - stub
      - run: exit 0

  filteredMatrixJobStub:
    name: Filtered Matrix Job ${{ matrix.a }} - ${{ matrix.b }}
    needs: prFilter
    if: needs.prFilter.outputs.success != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: ['a', 'b']
        b: [0, 1]

    steps:
      - run: echo ${{ matrix.a }} - ${{ matrix.b }} - stub
      - run: exit 0
