name: Publish

on:
  push:
    branches:
      - "*"

jobs:

  hello:

    runs-on: ubuntu-latest
    name: Hello
    
    steps:

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          
      - name: Publish
        run: npm dist-tag add devextreme-internal-tools@2.2.1 latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
