name: Publish

on:
  push:
    branches:
      - "*"

env:
  nodeVersion: 12.x

jobs:

  hello:

    runs-on: ubuntu-latest
    name: Hello
    
    steps:

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}
          
      - name: Print
        run: echo ${{ secrets.TEST_TOKEN2 }}

      - name: Print 3
        run: cat .npmrc
        
      - name: Print 2
        run: echo ${TTT_TOKEN}
        env:
          TTT_TOKEN: ${{ secrets.TEST_TOKEN }}
          
      - name: Publish
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
