name: Publishing to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      pattern:
        type: string
        description: grep pattern
        required: false

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
    
      - name: Get tarball from npmjs.org
        run: |
          npm pack devextreme@23.2.2-beta
          tar -xzf devextreme-23.2.2-beta.tgz
          
      - name: Update package.json
        working-directory: package
        run: |
          sed -i '/\"repository\"/,/}/ d; /^$/d' package.json
          npm init -y --scope ${{ github.repository_owner }}

      - name: Repack
        working-directory: package
        run: |
          npm pack --pack-destination="../"

      - name: ls
        run: ls | grep --extended-regexp --ignore-case '${{ inputs.pattern }}' |
          while read filename; do
            stat ${filename};
          done

      # - name: Publish to npm.pkg.github.com
      #   working-directory: package
      #   run: npm publish --registry https://npm.pkg.github.com --access=restricted
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
