name: Publishing to GitHub Packages

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
    
      - name: Get tarball from npmjs.org
        run: |
          npm pack devextreme@23.2.2-beta
          tar -xzf devextreme-23.2.2-beta.tgz
          
      - name: Remove the repository field
        working-directory: package
        run: |
          sed -i '/\"repository\"/,/}/ d; /^$/d' package.json
          npm pack --pack-destination="../"

      - name: Update scope
        working-directory: package
        run: npm init -y --scope ${{ github.repository_owner }}

      - run: cat $NPM_CONFIG_USERCONFIG

      - name: Publish to npm.pkg.github.com
        run: npm publish --dry-run --scope=@${{ github.repository_owner }} devextreme-23.2.2-beta.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
