name: Publish

on:
  push:
    branches:
      - releases/*

jobs:

  version-check:

    runs-on: ubuntu-latest
    name: Check Version
    outputs:
      changed: ${{ steps.check.outputs.previous-version != steps.check.outputs.current-version }}

    steps:

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check version
        id: check
        uses: salsify/action-detect-and-tag-new-version@v2

  publishing:

    name: Publish
    needs: [ version-check ]
    runs-on: windows-latest
    if: needs.version-check.outputs.changed == 'true'

    steps:

      - name: Publish
        run: echo ${{ needs.version-check.outputs.changed }}
