name: Publish

on:
  push:
    branches:
      - releases/*

jobs:

  publishing:

    runs-on: ubuntu-latest
    name: Publish if Version Bumped

    steps:

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check Version
        id: version
        uses: salsify/action-detect-and-tag-new-version@v2

      - name: Publish
        if: steps.version.outputs.current-version != steps.version.outputs.previous-version
        run: echo Publishing...
