name: Publish

on:
  push:
    branches:
      - "*"

jobs:

  hello:

    runs-on: windows-latest
    name: Hello
    
    steps:

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nodeVersion }}
          
      - name: Publish
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
