name: Publishing to GitHub Packages

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@ilyakhd'
    
      - name: Get tarball from npmjs.org
        run: |
          npm pack devextreme@23.2.2-beta
          tar -xzf devextreme-23.2.2-beta.tgz
          
      - name: Remove the repository field
        working-directory: package
        run: |
          sed -i '/\"repository\"/,/}/ d; /^$/d' package.json
          npm pack --pack-destination="../"

      - run: cat $NPM_CONFIG_USERCONFIG
