name: Publish

on:
  push:
    paths:
      - package.json

jobs:

  check-version-bump:

    runs-on: ubuntu-latest
    name: Check Version Bump 
    outputs:
      changed: ${{ steps.detection.outputs.changed }}
      version: ${{ steps.detection.outputs.version }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect Bump
        id: detection
        run: |
          versionDiff=$( git diff HEAD^ HEAD -U0 package.json )
          if ! [[ $versionDiff ]] || ! [[ $versionDiff =~ (\+ *\"version\":) ]]
          then
            echo "::debug::Version didn't change"
            exit 0
          fi
          
          echo "::set-output name=changed::true"
          echo "::set-output name=version::$( echo $versionDiff | grep -oP "\+ *\"version\":.+," | grep -oP "\d+\.\d+.\d+" )"
          
      - name: print
        run: |
          echo ${{ steps.detection.outputs.changed }}
          echo ${{ steps.detection.outputs.version }}
         
  publish:

    name: Publish
    needs: [ check-version-bump ]
    runs-on: windows-latest
    if: needs.version-check.outputs.changed == 'true'

    steps:
      - run: echo ${{needs.version-check.outputs.version}}
