name: Publish

on:
  push:
    branches:
      - releases/*

jobs:

  publishing:

    runs-on: windows-latest
    name: Publish if Version Bumped
    
    steps:

      - name: Check Version
        uses: EndBug/version-check@v2
        id: version-check
        with:
          diff-search: false

      - name: Publish
        if: steps.version-check.outputs.changed == 'true'
        run: echo publishing...
