name: Publishing to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      pattern:
        type: string
        description: grep pattern
        required: false

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
    
      - name: Get tarball from npmjs.org
        run: npm pack devextreme@23.2.2-beta

      - name: Publish to npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ls *.tgz | grep --extended-regexp --ignore-case '${{ inputs.pattern }}' |
          while read filename; do
            tar -xzf ${filename};
            pushd package;
            sed -i '/\"repository\"/,/}/ d; /^$/d' package.json;
            npm init -y --scope ${{ github.repository_owner }};
            npm publish --dry-run --registry https://npm.pkg.github.com;
            popd;
            rm -r package;
          done
