name: Publish
on:
  push:
    paths:
      - package.json
jobs:

  check-version-bump:
    runs-on: ubuntu-latest
    name: Check Version Bump 
    outputs:
      changed: ${{ steps.detection.outputs.changed }}
      version: ${{ steps.detection.outputs.version }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect Bump
        id: detection
        uses: ./.github/actions/detect-version-bump

  publish:
    name: Publish
    needs: [ check-version-bump ]
    runs-on: windows-latest
    if: needs.check-version-bump.outputs.changed == 'true'
    steps:

      - run: echo ${{needs.check-version-bump.outputs.version}}
