name: Publishing to GitHub Packages

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
    
      - name: Get tarball from npmjs.org
        run: |
          npm pack devextreme@23.2.2-beta
          tar -xzf devextreme-23.2.2-beta.tgz
          
      - name: Remove the repository field
        working-directory: package
        run: |
          sed -i '/\"repository\"/,/}/ d; /^$/d' package.json
          npm pack --pack-destination="../"

      - name: Publish to npm.pkg.github.com
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
