name: PR
on: pull_request

jobs:

  check-version-pr:
    name: No other changes if version bumped
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Detect version bump
        id: versionBump
        uses: ./.github/actions/detect-version-bump

      - name: Check for other changes
        if: steps.versionBump.outputs.changed       
        run: |
          stat=$(git diff HEAD^ HEAD --shortstat)
          
          if ! [[ "$stat" =~ (1 *file *changed.*1 *insertion.*1 *deletion) ]]
          then
            echo "PR with version bump must have no other changes"
            exit 1
          fi
