name: Version
on:
  pull_request:
    paths:
      - package.json
jobs:

  version-bump:
    runs-on: ubuntu-latest
    name: Detect version bump 
    outputs:
      changed: ${{ steps.detection.outputs.changed }}
      version: ${{ steps.detection.outputs.version }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect Bump
        id: detection
        uses: ./.github/actions/detect-version-bump

  title-matches-bumped-version:
    name: Title matches bumped version
    runs-on: ubuntu-latest
    needs: [ version-bump ]
    if: needs.version-bump.outputs.changed
    steps:

      - name: Check title
        if: github.event.pull_request.title != needs.version-bump.outputs.version
        run: |
            echo "Title must match new version"
            exit 1

  no-other-changes-if-version-bumped:
    name: No other changes if version bumped
    runs-on: ubuntu-latest
    needs: [ version-bump ]
    if: needs.version-bump.outputs.changed
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check for other changes
        run: |         
          if ! [[ $(git diff HEAD^ HEAD --shortstat) =~ (1 *file *changed.*1 *insertion.*1 *deletion) ]]
          then
            echo "PR with version bump must have no other changes"
            exit 1
          fi
